version: "3.9"
services:
  postgres:
    container_name: postgres    
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - backend/docker.env
    networks:
      - postgres 
    restart: always

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - backend/docker.env
    networks:
      - postgres  
    restart: always

  frontend:
    container_name: frontend
    depends_on:
    - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    stdin_open: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
    - "80:80"
    networks:
    - postgres 
    restart: always

  backend:
    container_name: backend
    links:
    - postgres:postgres
    depends_on:
    - postgres
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
    - "3001:3001"
    networks:
    - postgres 
    restart: always

networks:
  postgres:
    driver: bridge